# Generated by Django 2.0.2 on 2018-04-25 13:52

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180425_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photu',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='User', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
