# Generated by Django 2.0.2 on 2018-04-07 19:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'atleast 5 characters')])),
                ('code_text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'atleast 3 characters')])),
            ],
        ),
    ]
