# Generated by Django 2.0.2 on 2018-04-07 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'atleast 5 characters')])),
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('code_text', models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'atleast 3 characters')])),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
