# Generated by Django 2.0.2 on 2018-04-09 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20180407_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.TextField(choices=[('automation', 'automation'), ('software', 'software'), ('android', 'android')], default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
