# Generated by Django 2.0.2 on 2018-04-23 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_one', '0007_auto_20180423_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='userholder', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
