# Generated by Django 2.0.2 on 2018-04-23 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_comment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=250, validators=[django.core.validators.MinLengthValidator(3, 'atleast 3 characters')]),
        ),
    ]
