# Generated by Django 2.0.2 on 2018-04-23 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0010_auto_20180423_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(3, 'atleast 3 characters')]),
        ),
    ]
