# Generated by Django 2.0.2 on 2018-04-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0011_auto_20180423_1502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-timestamp']},
        ),
    ]
