# Generated by Django 2.0.2 on 2018-04-23 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0012_auto_20180423_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['timestamp']},
        ),
    ]
